Feature/cmob 2002 build UI
Niklaus2000/Movies pull request #1
Opened 2023-08-15 11:00 UTC by Niklaus2000

-Design https://www.figma.com/file/UgTXNAXH2ScX6OHRREkSIZ/Designs-for-interns?type=design&node-id=186-2032&mode=design&t=aYKP2D4PTvaGbYqY-0
-Task Review https://spaceneobank.atlassian.net/wiki/spaces/ABP/pages/854687782/Movie+App+-+iOS

2023-08-15 11:43 UTC, anadzebniauri commented on Movies/Core/Custom UI/SearchView/SearchView.swift
> +    }
search-ში როგორც კი დგები cancel მაშინვე უნდა დაეწეროს, წერას რო იწყებ მაშინ იწერება

2023-08-15 11:44 UTC, anadzebniauri commented on Movies/Scene/HomeViewController/CollectionView/GenreCollectionViewCell/CollectionViewCell+Constants/GenreCollectionViewCell+Constants.swift
> +        enum GenreLabelView {
ტექსტი გასაცენტრია

2023-08-15 11:46 UTC, anadzebniauri commented on Movies/Core/Custom UI/FilterImageView/FilterButtonView.swift
> +final class FilterButtonView: UIButton {
ფილტრს რო ჩამოშლი და სერჩის ველში ჩადგები ფილტრის ღილაკი cancel-ით უნდა ჩანაცვლდეს და კატეგორიები უნდა გაქრეს, ქენსილის დაჭერის შემდეგ ჩვეულებრივ სთეითში უნდა დაბრუნდეს

2023-08-15 11:47 UTC, anadzebniauri commented on Movies/Scene/FavoriteViewController/FavoriteCollectionViewCell/FavoriteCollectionViewCell.swift
> +
ქვედა კონსტრეინტი არაა გაწეტილი, ნავიგაციის ღილაკები ქოლექშენ ვიუს ადევს ზემოდან

2023-08-15 11:48 UTC, anadzebniauri commented on Movies/Scene/HomeViewController/HomeViewController.swift
> +    private lazy var movieGenreCollectioView: UICollectionView = {
ნავიგაციის ღილაკები აქაც ზემოდან ადევს ქოლექშენ ვიუს

2023-08-15 11:49 UTC, anadzebniauri commented on Movies/Scene/MovieDetailsController/MovieDetailsController.swift
> +    private lazy var genreLabel: UILabel = {
ამ ლეიბლებს პადინგები არ აქვს, დაშორებული უნდა იყოს ტექსტი უკანა ბექგრაუნდს როგორც დიზაინშია

2023-08-15 11:50 UTC, anadzebniauri commented on Movies/Scene/MovieDetailsController/MovieDetailsController.swift
> +    private lazy var favoriteButton: UIButton = {
დიზაინში ნახე მეორე შედარებით დიდი ზომის გულებია და დეტალების გვერდზე ისინი უნდა გასეტო, იგივე არა რაც ჰოუმის გვერდზე

2023-08-15 11:55 UTC, anadzebniauri commented on Movies/Scene/HomeViewController/HomeViewController.swift
> +    private let moviesLabelView: UILabel = {
ვიზუალურად კონსტრეინტი არ ჩანს რო გაწერილია, უფრო დაშორებული უნდა იყოს Moviesდა ქოლექშენ ვიუ

2023-08-15 11:58 UTC, anadzebniauri commented on Movies/Scene/HomeViewController/HomeViewController+Constants/HomeViewController+Constants.swift
> +extension HomeViewController {
ფონტიც გაუწერე ყველაფერს თავისი ზომებით, ძალიან პატარა ფონტია

2023-08-15 12:00 UTC, Niklaus2000 commented on Movies/Core/Custom UI/SearchView/SearchView.swift
> +    }
  cancel-ის ფუნქციონალი არის, რომ ინფუთი ერთიანად წაშალოს. თუ მაშინ გამოჩნდება cancel, როდესაც ჩადგები და არა როდესაც რაიმე დაიწერება, გამოვა რომ ცარიელი სერჩი შემიძლია დავაქენსელო, რაც ისედაც ცარიელია კი ვეღარ დაცარიელდება. აქედან გამომდინარე, ფუნქციონალი არ უნდა გამოჩნდეს ისეთ დროს, როდესაც ვერაფერს შეასრულებს.

2023-08-15 12:00 UTC, anadzebniauri commented
სახელი შეუცვალე პრ-ს [CMOB-2002]Feature: Build UI

2023-08-15 12:13 UTC, anadzebniauri commented on Movies/Core/Custom UI/SearchView/SearchView.swift
> +    }
ჩემი აზრით, სერჩში ჩადგომის დროს უნდა დაეწეროს ქენსილი, შეგიძლია გაარკვიო ეგ საკითხი

2023-08-15 12:54 UTC, tivanashvili requested changes
1)სერჩში რო დგები ქენსელი არ ჩანს, მარტო წერას რო იწყებ მაშინ ჩანს 
2)ქენსელს რო აწვები არ შლის ჩაწერილ ტექსტს
3)როცა ჟანრების ქოლექშენვიუ ჩანს და მაგ დროს დგები სერჩში ეს ქოლქშენვიუ არ უნდა ჩანდეს
4)სერჩში ფლეისჰოლდერი არ ჩანს
5) ჟანრების ლეიბლები არაა გაცენტრილი
6)როცა ჟანრების სელს ასელექთებ ბორდერ ქოლორი იგივე რჩება, თეთრია, წესით ბორდერ ქოლორი უნდა ქრებოდეს

2023-08-15 12:54 UTC, tivanashvili commented on Movies/Scene/FavoriteViewController/FavoriteViewController.swift
> +    private var errorStateView: ErrorStateView = {
private let

2023-08-15 12:54 UTC, tivanashvili commented on Movies/Scene/FavoriteViewController/FavoriteViewController.swift
> +    private var emptyStateView: EmptyStateView = {
private let

2023-08-15 12:54 UTC, tivanashvili commented on Movies/Scene/HomeViewController/CollectionView/GenreCollectionViewCell/MovieGenreCollectionViewCell.swift
> +    var isCellSelected: Bool = false {
ro daselectdeba cell border color unda gaqres, exla chans tetri bordercolor kvitel ponze

2023-08-15 12:54 UTC, tivanashvili commented on Movies/Scene/HomeViewController/HomeViewController.swift
> +    private var titleLabelTopConstraint: NSLayoutConstraint!
safe unwrap

2023-08-15 12:54 UTC, tivanashvili commented on Movies/Scene/MovieDetailsController/MovieDetailsController.swift
> +    private lazy var stackView: UIStackView = {
aq lazy ar gchirdeba, private let

2023-08-15 12:54 UTC, tivanashvili commented on Movies/Scene/MovieDetailsController/MovieDetailsController.swift
> +        self.title = "Details"
es constantebshi gaitane

2023-08-15 12:54 UTC, tivanashvili commented on Movies/Core/Custom UI/SearchView/SearchView.swift
> +        textField.addTarget(self, action: #selector(textFieldDidChange(_:)), for: .editingChanged)
aq addtarget ro aketeb >self Aris tviton SearchView, amito aq addtarget ro moxdes an calke func-shi unda gaitano da iq gamoidzaxo an lazy var daucero

2023-08-15 12:54 UTC, tivanashvili commented on Movies/Core/Custom UI/TabBarEnum/TabBarEnum.swift
> +                named:"tab_bar_home_UNSelected")?
esenic constantebshi gaitane

2023-08-15 13:23 UTC, anadzam reviewed
vizualuri bugebia bevri, dizains sheadare kvela screeni. fontebis zomebi perebi da weightebi naxe kargad. tabbarze problemaa. danarcheni detalurad dagicere

2023-08-15 13:23 UTC, anadzam commented on Movies/Core/Custom UI/SearchView/SearchView.swift
> +    private let textField: UITextField = {
warningi gak self ze da gchirdeba private lazy var

2023-08-15 13:23 UTC, anadzam commented on Movies/Core/Custom UI/SearchView/SearchView.swift
> +    func clearSearchText() {
es punkcia ar mushaobs scorad. Rogorc ki chadgebi unda krebodes filter buttoni da chndebodes cancel. shen shemtxvevashi sanam ar akripav rames ar chndeba cancel buttoni. aseve cancels ro acher ar aclearebs searchbars.

2023-08-15 13:23 UTC, anadzam commented on Movies/Core/Custom UI/FilterImageView/FilterButtonView.swift
> +    private func filltredModeTapped() {
eseti bugia, tu filter buttons movnishnav da chavdgebi searchsshi, filter buttoni ar kreba da ar chndeba cancel butttoni.

2023-08-15 13:23 UTC, anadzam commented on Movies/Core/Custom UI/SearchView/SearchView.swift
ar gak keyboard dissmiss funkcia. anu tu searchshi var da sadme sxvagan davacher keyboardi unda gakres. aseve placeholderi ar gak scorad. arc peri da arc fonti. aseve serchshi ro dgebi egreve unda krebodes placeholdri.

2023-08-15 13:23 UTC, anadzam commented on Movies/Scene/HomeViewController/CollectionView/GenreCollectionViewCell/MovieGenreCollectionViewCell.swift
genrebis labelze texti ar gak gacentrili. aseve mgoni fontic sxvaari eg gadaamocme. aseve roca monishnav janrs, textis peri xdeba muki da aseve borderis peric kreba. shen shemtxvevashi ro vnishnav mxolod backgroundis peri icvleba. kide am fileshi kvela punkcia gadaakete privetad

2023-08-15 13:23 UTC, anadzam commented on Movies/Scene/HomeViewController/CollectionView/GenreCollectionViewCell/MovieGenreCollectionViewCell.swift
> +    let genreLabelView: UILabel = {
private let. ise saxelic genreLabel ikos radgan UILabel ari da ara UIView

2023-08-15 13:23 UTC, anadzam commented on Movies/Scene/HomeViewController/HomeViewController.swift
> +    private let moviesLabelView: UILabel = {
akac igive movieLabel upro kai saxelia radgan UILabel tipisaa da ara UIViewsi, es chemi azria. aseve es Movie Labeli dzalian axlosaa moviebis collection viewstan, dizains ar emtxveva

2023-08-15 13:23 UTC, anadzam commented on Movies/Scene/HomeViewController/CollectionView/GenreCollectionViewCell/CollectionViewCell+Constants/GenreCollectionViewCell+Constants.swift
es tu janrebis cellis constantebia mashin filesac unda erkvas ara genrecollectionviewCell+Constants aramed MovieGenreCollectionViewCell+Constants

2023-08-15 13:23 UTC, anadzam commented on Movies/Scene/HomeViewController/CollectionView/MovieCollectionViewCell/MoviesCollectionViewCell.swift
> +    private lazy var movieGenreLabel: UILabel = {
radiusi gadaamocme, cacvetebulia ro vranav. dizainshi momrgvalebulia

2023-08-15 13:23 UTC, anadzam commented on Movies/Scene/HomeViewController/CollectionView/MovieCollectionViewCell/MoviesCollectionViewCell.swift
> +    private lazy var movieNameLabel: UILabel = {
fontis sxvaari weightic da sizec

2023-08-15 13:23 UTC, anadzam commented on Movies/Scene/TabBarController/TabBarViewController.swift
tabbari vizualurad arascoradaaa. collections views adevs zemodan. dizainshi naxe rogorc aris

2023-08-15 13:23 UTC, anadzam commented on Movies/Core/Custom UI/FilterImageView/FilterButtonView.swift
tviton folders ro kvia filterImageView cota damabnevelia sxvistvis, filterButtonia da pirdapir eg daarkvi

2023-08-15 13:23 UTC, anadzam commented on Movies/Scene/MovieDetailsController/MovieDetailsController.swift
> +    private let moviePoster: UIImageView = {
posteri aris momrgvalebuli, sadgac gak gacerili corner radiusi. dizainshi ubralod potoa otxkutxedi

2023-08-15 13:23 UTC, anadzam commented on Movies/Scene/MovieDetailsController/MovieDetailsController.swift
![Simulator Screenshot - iPhone 14 - 2023-08-15 at 17 14 56](https://github.com/Niklaus2000/Movies/assets/84043643/4b47499f-a6d7-4ee0-9435-e2792f931898)
beri vizualuri bugia:
1. Details ro giceria navigation itemze eg ar aris centshi
2. gulis button pataraa designtan shedarebit
3. fonti da zomebi ar emtxveva dizains
4. ratingis da drois iconebi ar emtxveva dizains da paddingebic chirdeba imitoro drois labels cdeba textu da janris labelshic dzlivs eteva. t
5. about movie ro ceria magas background colori ak minihcbebuli
6.textebis perebi ar emtxveva. ar unda ikos tetri kvelgan, gadaxede dizains

2023-08-15 13:23 UTC, anadzam commented on Movies/Scene/FavoriteViewController/FavoriteViewController.swift
akac igive rac homeViewcontorllerze da tabbari akac adevs collectionviews.

2023-08-15 13:23 UTC, anadzam commented on Movies/Core/Custom UI/StatesView/EmptyStateView/EmptyStateView.swift
ar damitestavs rogor ari vizualurad da screenebi chaagde mashin

2023-08-15 13:23 UTC, anadzam commented on Movies/Core/Custom UI/StatesView/ErrorStateView/ErrorStateView.swift
ar damitestavs rogor ari vizualurad da screenebi chaagde mashin

2023-08-17 09:15 UTC, Niklaus2000 commented on Movies/Scene/HomeViewController/CollectionView/MovieCollectionViewCell/MoviesCollectionViewCell.swift
> +    private lazy var movieGenreLabel: UILabel = {
ფიგმას  მიხედვით 22 ია და ძაან წაწვეტებული ამიტომ 12 დავუსეტე უფრო ლამაზად ჩანს

2023-08-18 09:42 UTC, anadzebniauri commented on Movies/Scene/HomeViewController/CollectionView/GenreCollectionViewCell/CollectionViewCell+Constants/GenreCollectionViewCell+Constants.swift
> +        enum GenreLabelView {
აქ ტექსტს ისევ არ აქვს პადინგები რომ ლეიბლის ცენტრში იყოს, დიზაინს შეადარე

2023-08-18 09:46 UTC, anadzebniauri commented
1. პრ-ს შეუცვალე სახელი, წინა რევიუზე დაგიწერე რაც უნდა ერქვას
2. ტექსტები და პადინგები როგორც კატეგორიებზე ასევე ფილმის სახელებზე გასასწორებელია, ფონტი, ფონტის ზომა(ფილმის სახელი და წელი ძალიან დაშორებულია ერთმანეთისგან, დიზაინში ნახე)
3. როგორც ვიცი კატეგორიების დესელექტი არ უნდა შეგეძლოს( ამოცანაში არის now showing და coming soon, დეფოლტად სულ იქნება now showing ამიტომ დესელექტი არ უნდა ჰქონდეს)

2023-08-18 09:48 UTC, Niklaus2000 commented on Movies/Scene/HomeViewController/CollectionView/GenreCollectionViewCell/CollectionViewCell+Constants/GenreCollectionViewCell+Constants.swift
> +        enum GenreLabelView {
ლეიბლი გაცენტრილი მაქვს ოღონდ კონტროლერიდან. არ მაქვს კონსტანტებში  გაატანილი.

2023-08-21 08:57 UTC, anadzebniauri approved these changes

2023-08-22 09:50 UTC, anadzam approved these changes

2024-03-05 12:36 UTC, merged